# Generated by Django 4.0.3 on 2022-03-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editpdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='connnectionCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='pdf_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
