# Generated by Django 4.0.3 on 2022-03-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editpdf', '0002_pdffile_connnectioncount_pdffile_pdf_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdffile',
            old_name='connnectionCount',
            new_name='connectionCount',
        ),
    ]
